// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TriviaProject.Models;

namespace TriviaProject.Migrations
{
    [DbContext(typeof(TriviaContext))]
    [Migration("20210428173528_SecondMigrate")]
    partial class SecondMigrate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TriviaProject.Models.Duel", b =>
                {
                    b.Property<int>("DuelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("User1UserId")
                        .HasColumnType("int");

                    b.Property<int?>("User2UserId")
                        .HasColumnType("int");

                    b.Property<int>("UserId1")
                        .HasColumnType("int");

                    b.Property<int>("UserId2")
                        .HasColumnType("int");

                    b.HasKey("DuelId");

                    b.HasIndex("User1UserId");

                    b.HasIndex("User2UserId");

                    b.ToTable("Duels");
                });

            modelBuilder.Entity("TriviaProject.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TriviaProject.Models.Duel", b =>
                {
                    b.HasOne("TriviaProject.Models.User", "User1")
                        .WithMany("User2Duels")
                        .HasForeignKey("User1UserId");

                    b.HasOne("TriviaProject.Models.User", "User2")
                        .WithMany("User1Duels")
                        .HasForeignKey("User2UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
