// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TriviaProject.Models;

namespace TriviaProject.Migrations
{
    [DbContext(typeof(TriviaContext))]
    [Migration("20210427234953_FirstMigrate")]
    partial class FirstMigrate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TriviaProject.Models.Duel", b =>
                {
                    b.Property<int>("DuelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("UserId1UserId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId2UserId")
                        .HasColumnType("int");

                    b.HasKey("DuelId");

                    b.HasIndex("UserId1UserId");

                    b.HasIndex("UserId2UserId");

                    b.ToTable("Duels");
                });

            modelBuilder.Entity("TriviaProject.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TriviaProject.Models.Duel", b =>
                {
                    b.HasOne("TriviaProject.Models.User", "UserId1")
                        .WithMany()
                        .HasForeignKey("UserId1UserId");

                    b.HasOne("TriviaProject.Models.User", "UserId2")
                        .WithMany()
                        .HasForeignKey("UserId2UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
